### ISSUE TITLE
Remove calculations from OFFSET/FETCH

### ISSUE THREAD

**Issue by porterchris** [psibernetic/Susanoo#36]
Instead using calculated values for OFFSET/FETCH, use direct integer values.  The current format: 

    OFFSET (@PageNo - 1) * @PageSize ROWS
    FETCH NEXT @PageSize ROWS ONLY

Proposed format:

    OFFSET @Offset ROWS
    FETCH NEXT @Fetch ROWS ONLY

Not all code using OffsetFetch will be based on page numbers and page size values.  Because the formula is hard-coded, code that has start & length values will have to reverse calculate the page number and page size values so they can be converted back to the value as used in SQL.

Ideally the OffsetFetch<TFilter, TResult> (string, string) method would handle the new use and a new function for PageSizeNumber<TFilter, TResult> (string, string) could replace the existing calls.  This would be a breaking change but it might be early enough in its use that it wouldn't cause too much pain.

Thoughts?

**Comment by psibernetic** [comment]
What about introducing an additional optional parameter on OffsetFetch(string, string, bool computePage = true), so that the computation could be turned off. This would avoid a major version increment.

**Comment by psibernetic** [comment]
This issue is resolved in commit: e43d069c6ae4962127cba3910b9425423201ca7d. Review commit notes for implementation. If we agree on those changes I will queue up a release.
